/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lomba
 */
public class Game extends javax.swing.JFrame {
    
    private int level;
    /**
     * Creates new form Gioco
     */
    public Game(int level) {
        this.level = level;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eb_button = new javax.swing.JButton();
        e_button = new javax.swing.JButton();
        db_button = new javax.swing.JButton();
        c_button = new javax.swing.JButton();
        d_button = new javax.swing.JButton();
        cb_button = new javax.swing.JButton();
        f_button = new javax.swing.JButton();
        ab_button = new javax.swing.JButton();
        g_button = new javax.swing.JButton();
        bb_button = new javax.swing.JButton();
        a_button = new javax.swing.JButton();
        b_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(250, 380));
        setPreferredSize(new java.awt.Dimension(250, 380));
        setSize(new java.awt.Dimension(250, 380));
        getContentPane().setLayout(null);

        eb_button.setBackground(new java.awt.Color(0, 0, 0));
        eb_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eb_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(eb_button);
        eb_button.setBounds(60, 180, 19, 77);

        e_button.setBackground(new java.awt.Color(255, 255, 255));
        e_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(e_button);
        e_button.setBounds(70, 190, 30, 130);

        db_button.setBackground(new java.awt.Color(0, 0, 0));
        db_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                db_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(db_button);
        db_button.setBounds(30, 180, 19, 77);

        c_button.setBackground(new java.awt.Color(255, 255, 255));
        c_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(c_button);
        c_button.setBounds(10, 190, 30, 130);

        d_button.setBackground(new java.awt.Color(255, 255, 255));
        d_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(d_button);
        d_button.setBounds(40, 190, 30, 130);

        cb_button.setBackground(new java.awt.Color(0, 0, 0));
        cb_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(cb_button);
        cb_button.setBounds(120, 180, 19, 77);

        f_button.setBackground(new java.awt.Color(255, 255, 255));
        f_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(f_button);
        f_button.setBounds(100, 190, 30, 130);

        ab_button.setBackground(new java.awt.Color(0, 0, 0));
        ab_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ab_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(ab_button);
        ab_button.setBounds(150, 180, 19, 77);

        g_button.setBackground(new java.awt.Color(255, 255, 255));
        g_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(g_button);
        g_button.setBounds(130, 190, 30, 130);

        bb_button.setBackground(new java.awt.Color(0, 0, 0));
        bb_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bb_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(bb_button);
        bb_button.setBounds(180, 180, 19, 77);

        a_button.setBackground(new java.awt.Color(255, 255, 255));
        a_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(a_button);
        a_button.setBounds(160, 190, 30, 130);

        b_button.setBackground(new java.awt.Color(255, 255, 255));
        b_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(b_button);
        b_button.setBounds(190, 190, 30, 130);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void e_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_buttonActionPerformed

    private void eb_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eb_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eb_buttonActionPerformed

    private void c_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_buttonActionPerformed

    private void d_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d_buttonActionPerformed

    private void db_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_db_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_db_buttonActionPerformed

    private void f_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_buttonActionPerformed

    private void cb_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_buttonActionPerformed

    private void g_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g_buttonActionPerformed

    private void ab_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ab_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ab_buttonActionPerformed

    private void a_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_buttonActionPerformed

    private void bb_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bb_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bb_buttonActionPerformed

    private void b_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a_button;
    private javax.swing.JButton ab_button;
    private javax.swing.JButton b_button;
    private javax.swing.JButton bb_button;
    private javax.swing.JButton c_button;
    private javax.swing.JButton cb_button;
    private javax.swing.JButton d_button;
    private javax.swing.JButton db_button;
    private javax.swing.JButton e_button;
    private javax.swing.JButton eb_button;
    private javax.swing.JButton f_button;
    private javax.swing.JButton g_button;
    // End of variables declaration//GEN-END:variables
}
