/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lomba
 */
import jm.JMC;
import jm.constants.*;
import jm.music.data.*;
import jm.util.Play;
import jm.util.View;

public class Game extends javax.swing.JFrame implements JMC {
    
    private int level=1;
    private int score=0;
    private int bpm;
    private int error=0;
    
    private int currentNote;
    private int[] pitch;// = new int[4];
    
    /**
     * Creates new form Game
     */
    public Game(int level) {
        this.level = level;
        initComponents();
        generateNote();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eb_button = new javax.swing.JButton();
        e_button = new javax.swing.JButton();
        db_button = new javax.swing.JButton();
        c_button = new javax.swing.JButton();
        d_button = new javax.swing.JButton();
        cb_button = new javax.swing.JButton();
        f_button = new javax.swing.JButton();
        ab_button = new javax.swing.JButton();
        g_button = new javax.swing.JButton();
        bb_button = new javax.swing.JButton();
        a_button = new javax.swing.JButton();
        b_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        score_label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bpm_label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        level_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(250, 380));
        setMinimumSize(new java.awt.Dimension(250, 380));
        setPreferredSize(new java.awt.Dimension(250, 380));
        setSize(new java.awt.Dimension(250, 380));
        getContentPane().setLayout(null);

        eb_button.setBackground(new java.awt.Color(0, 0, 0));
        eb_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eb_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(eb_button);
        eb_button.setBounds(60, 180, 19, 77);

        e_button.setBackground(new java.awt.Color(255, 255, 255));
        e_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(e_button);
        e_button.setBounds(70, 190, 30, 130);

        db_button.setBackground(new java.awt.Color(0, 0, 0));
        db_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                db_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(db_button);
        db_button.setBounds(30, 180, 19, 77);

        c_button.setBackground(new java.awt.Color(255, 255, 255));
        c_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(c_button);
        c_button.setBounds(10, 190, 30, 130);

        d_button.setBackground(new java.awt.Color(255, 255, 255));
        d_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(d_button);
        d_button.setBounds(40, 190, 30, 130);

        cb_button.setBackground(new java.awt.Color(0, 0, 0));
        cb_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(cb_button);
        cb_button.setBounds(120, 180, 19, 77);

        f_button.setBackground(new java.awt.Color(255, 255, 255));
        f_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(f_button);
        f_button.setBounds(100, 190, 30, 130);

        ab_button.setBackground(new java.awt.Color(0, 0, 0));
        ab_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ab_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(ab_button);
        ab_button.setBounds(150, 180, 19, 77);

        g_button.setBackground(new java.awt.Color(255, 255, 255));
        g_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(g_button);
        g_button.setBounds(130, 190, 30, 130);

        bb_button.setBackground(new java.awt.Color(0, 0, 0));
        bb_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bb_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(bb_button);
        bb_button.setBounds(180, 180, 19, 77);

        a_button.setBackground(new java.awt.Color(255, 255, 255));
        a_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(a_button);
        a_button.setBounds(160, 190, 30, 130);

        b_button.setBackground(new java.awt.Color(255, 255, 255));
        b_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(b_button);
        b_button.setBounds(190, 190, 30, 130);

        jLabel1.setText("Score:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 30, 13);

        score_label.setText("0");
        getContentPane().add(score_label);
        score_label.setBounds(40, 10, 10, 13);

        jLabel2.setText("BPM:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 10, 23, 13);
        getContentPane().add(bpm_label);
        bpm_label.setBounds(190, 10, 10, 10);

        jLabel3.setText("Level:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 10, 27, 13);

        level_label.setText("1");
        getContentPane().add(level_label);
        level_label.setBounds(100, 10, 10, 13);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void e_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_buttonActionPerformed
        if (currentNote==E0){
            addScore();
        }else{
            addError();
        }
    }//GEN-LAST:event_e_buttonActionPerformed

    private void eb_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eb_buttonActionPerformed
        if (currentNote==EF0){
            addScore();
        }else{
            addError();
        }
    }//GEN-LAST:event_eb_buttonActionPerformed

    private void c_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_buttonActionPerformed
        if (currentNote==C0){
            addScore();
        }else{
            addError();
        }
    }//GEN-LAST:event_c_buttonActionPerformed

    private void d_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d_buttonActionPerformed
        if (currentNote==D0){
            addScore();
        }else{
            addError();
        }
    }//GEN-LAST:event_d_buttonActionPerformed

    private void db_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_db_buttonActionPerformed
        if (currentNote==DF0){
            addScore();
        }else{
            addError();
        }
    }//GEN-LAST:event_db_buttonActionPerformed

    private void f_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_buttonActionPerformed
        if (currentNote==F0){
            addScore();
        }else{
            addError();
        }
    }//GEN-LAST:event_f_buttonActionPerformed

    private void cb_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_buttonActionPerformed
        if (currentNote==CF0){
            addScore();
        }else{
            addError();
        }
    }//GEN-LAST:event_cb_buttonActionPerformed

    private void g_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g_buttonActionPerformed
        if (currentNote==G0){
            addScore();
        }else{
            addError();
        }
    }//GEN-LAST:event_g_buttonActionPerformed

    private void ab_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ab_buttonActionPerformed
        if (currentNote==AF0){
            addScore();
        }else{
            addError();
        }
    }//GEN-LAST:event_ab_buttonActionPerformed

    private void a_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_buttonActionPerformed
        if (currentNote==A0){
            addScore();
        }else{
            addError();
        }
    }//GEN-LAST:event_a_buttonActionPerformed

    private void bb_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bb_buttonActionPerformed
        if (currentNote==BF0){
            addScore();
        }else{
            addError();
        }
    }//GEN-LAST:event_bb_buttonActionPerformed

    private void b_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_buttonActionPerformed
        if (currentNote==B0){
            addScore();
        }else{
            addError();
        }
    }//GEN-LAST:event_b_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /*new Game(1).setVisible(true);
                int[] pitch = {C0,B0,F0,A0};
                double[] durations = {C,C,C,C};
                Phrase phrase = new Phrase();
                phrase.addNoteList(pitch,durations);
                View.show(phrase);*/
            }
        });
    }
    
    private void generateNote(){
        //DA CAMBIARE
        int []pitch2 = {C0,B0,F0,A0};
        this.pitch = pitch2;
        
        this.currentNote = pitch[0];
        
        double[] durations = {C,C,C,C};
        Phrase phrase = new Phrase();
        phrase.addNoteList(pitch2,durations);
        View.notate(phrase);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a_button;
    private javax.swing.JButton ab_button;
    private javax.swing.JButton b_button;
    private javax.swing.JButton bb_button;
    private javax.swing.JLabel bpm_label;
    private javax.swing.JButton c_button;
    private javax.swing.JButton cb_button;
    private javax.swing.JButton d_button;
    private javax.swing.JButton db_button;
    private javax.swing.JButton e_button;
    private javax.swing.JButton eb_button;
    private javax.swing.JButton f_button;
    private javax.swing.JButton g_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel level_label;
    private javax.swing.JLabel score_label;
    // End of variables declaration//GEN-END:variables

    private void addScore() {
        //this.score++;
        score_label.setText(Integer.toString(++score));
        //GENERA NOTA NUOVA SUCCESSIVA
        this.currentNote = B0;
    }

    private void addError() {
        this.error++;
        //AGGIUNGERE GESTIONE ERRORI
        score_label.setText(Integer.toString(--score));
    }
}
